version: 0.9.7.{build}

clone_folder: c:\dev\HdrHistogram_c


environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: Visual Studio 15 2017
    CFG: Release
    VSINSTALL: '"Microsoft Visual Studio"/2017/Community/VC/Auxiliary/Build'
    MSVC_PLATFORM: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: Visual Studio 15 2017
    CFG: Release
    VSINSTALL: '"Microsoft Visual Studio"/2017/Community/VC/Auxiliary/Build'
    MSVC_PLATFORM: amd64
 
install:
  - cd c:\dev
  - md c:\dev\zlib64
  - ps: Start-FileDownload 'http://zlib.net/zlib-1.2.11.tar.gz'
  - 7z x zlib-1.2.11.tar.gz
  - 7z x zlib-1.2.11.tar

build:

build_script:
  - cd c:\dev\zlib-1.2.11
  - md build%MSVC_PLATFORM%
  - cd build%MSVC_PLATFORM%
  - cmake -DCMAKE_INSTALL_PREFIX=c:\dev\zlib%MSVC_PLATFORM% -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CFG% ..
  - cmake --build . --target install --config "%CFG%"
  - dir c:\dev\zlib%MSVC_PLATFORM%
  - cd c:\dev\HdrHistogram_c
  - md build%MSVC_PLATFORM%
  - cd build%MSVC_PLATFORM%
  - cmake -DZLIB_LIBRARY="C:\DEV\zlib%MSVC_PLATFORM%\lib\zlibstatic.lib" -DZLIB_INCLUDE_DIR="C:\DEV\zlib%MSVC_PLATFORM%\include" -G "%GENERATOR%" ..
  - cmake --build . --config "%CFG%"

test_script:
  - cd c:\dev\HdrHistogram_c\build%MSVC_PLATFORM%
  - cmd: ctest
